/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GIAODIEN.KHACHANG;

/**
 *
 * @author Cam Tien
 */
public class KHACHHANGDANGKI extends javax.swing.JFrame {

    /**
     * Creates new form KHACHHANG
     */
    public KHACHHANGDANGKI() {
         this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DKITAIKHOAN = new javax.swing.JLabel();
        CCCD = new javax.swing.JLabel();
        TEN = new javax.swing.JLabel();
        std = new javax.swing.JLabel();
        GTINH = new javax.swing.JLabel();
        ngsinh = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jTfCCD = new javax.swing.JTextField();
        jTfHoVaTen = new javax.swing.JTextField();
        jTfSdt = new javax.swing.JTextField();
        jTfGioiTinh = new javax.swing.JTextField();
        jTfNgaySinh = new javax.swing.JTextField();
        jTfEmail = new javax.swing.JTextField();
        JBtnDangKi = new javax.swing.JButton();
        jBtnThoat = new javax.swing.JButton();
        diachi = new javax.swing.JLabel();
        jTfDiaChi = new javax.swing.JTextField();
        diachi1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DKITAIKHOAN.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        DKITAIKHOAN.setText("ĐĂNG KÍ TÀI KHOẢN KHÁCH HÀNG");

        CCCD.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        CCCD.setText("CCCD:");

        TEN.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        TEN.setText("Họ và tên:");

        std.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        std.setText("SDT:");

        GTINH.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        GTINH.setText("Giới tính:");

        ngsinh.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        ngsinh.setText("Ngày sinh:");

        email.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        email.setText("Email:");

        JBtnDangKi.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        JBtnDangKi.setText("ĐĂNG KÍ");

        jBtnThoat.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnThoat.setText("Thoát");

        diachi.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        diachi.setText("Địa chỉ:");

        diachi1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        diachi1.setText("Mật Khẩu");

        jPasswordField1.setText("jPasswor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(DKITAIKHOAN)
                .addGap(0, 112, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CCCD)
                            .addComponent(std)
                            .addComponent(TEN)
                            .addComponent(GTINH)
                            .addComponent(ngsinh)
                            .addComponent(email)
                            .addComponent(diachi)
                            .addComponent(diachi1))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTfCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jTfHoVaTen)
                            .addComponent(jTfSdt)
                            .addComponent(jTfGioiTinh)
                            .addComponent(jTfNgaySinh)
                            .addComponent(jTfEmail)
                            .addComponent(jTfDiaChi)
                            .addComponent(jPasswordField1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBtnDangKi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnThoat)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(DKITAIKHOAN)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCCD)
                    .addComponent(jTfCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEN)
                    .addComponent(jTfHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std)
                    .addComponent(jTfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GTINH)
                    .addComponent(jTfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngsinh)
                    .addComponent(jTfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(jTfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diachi)
                    .addComponent(jTfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diachi1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnThoat)
                    .addComponent(JBtnDangKi))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGDANGKI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGDANGKI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGDANGKI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHACHHANGDANGKI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHACHHANGDANGKI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCCD;
    private javax.swing.JLabel DKITAIKHOAN;
    private javax.swing.JLabel GTINH;
    private javax.swing.JButton JBtnDangKi;
    private javax.swing.JLabel TEN;
    private javax.swing.JLabel diachi;
    private javax.swing.JLabel diachi1;
    private javax.swing.JLabel email;
    private javax.swing.JButton jBtnThoat;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTfCCD;
    private javax.swing.JTextField jTfDiaChi;
    private javax.swing.JTextField jTfEmail;
    private javax.swing.JTextField jTfGioiTinh;
    private javax.swing.JTextField jTfHoVaTen;
    private javax.swing.JTextField jTfNgaySinh;
    private javax.swing.JTextField jTfSdt;
    private javax.swing.JLabel ngsinh;
    private javax.swing.JLabel std;
    // End of variables declaration//GEN-END:variables
}
